version: '3.8'

services:
  streamlit:
    image: python:3.10
    container_name: streamlit_app
    build: .
    command: streamlit run app.py
    volumes:
      - .:/app  # Monta o diretório atual no container
    ports:
      - "80:8501"  # Mapeia a porta 80 do host para a porta 8501 do container
    working_dir: /app  # Define o diretório de trabalho
    environment:
      - STREAMLIT_SERVER_PORT=8501
    networks:
      - streamlit_network
    restart: always

networks:
  streamlit_network:
    driver: bridge
