version: '3.8'

services:
  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "80:8501"  # Mapeia a porta 80 do host para a porta 8501 do container
    volumes:
      - .:/app  # Monta o diretório atual no container
    networks:
      - streamlit_network
    restart: always

networks:
  streamlit_network:
    driver: bridge
